# Generated by Django 5.0.4 on 2024-04-11 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('info', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Participation_in_events',
            fields=[
                ('participation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='', max_length=20)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Var2.events')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Var2.participants')),
            ],
        ),
    ]
